apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Values.dnsHostName}} ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/grpc-services: "grpc-svc"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #certmanager.k8s.io/acme-dns01-provider: prod-clouddns
    #certmanager.k8s.io/acme-challenge-type: dns01
    cert-manager.io/issuer: "letsencrypt-production"
    #ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: "{{.Values.dnsHostName}}"
    http:
      paths:
      - backend:
          serviceName: "{{.Values.fleetName}}"
          servicePort: {{ .Values.fleetSvcExtPort }}
  tls:
  - hosts:
    - "{{.Values.dnsHostName}}"
    secretName: "{{.Values.fleetName}}-https"
