name: fleet
version: 2.6.0
appVersion: 2.6.0
description: Kolide Fleet is a state of the art host monitoring platform tailored for security experts. Leveraging Facebook's battle-tested osquery project, Kolide delivers fast answers to big questions. To learn more about the Kolide Fleet, visit https://kolide.com/fleet.
keywords:
- kolide
- fleet
- osquery
- tls-server
home: https://kolide.com/fleet
sources:
- https://github.com/kolide/fleet
- https://github.com/kubernetes/charts
